modification du fichier docker prod

diff --git a/Dockerfile.prod b/Dockerfile.prod
--- a/Dockerfile.prod
+++ b/Dockerfile.prod
@@ -31,7 +31,7 @@ ENV NEXT_TELEMETRY_DISABLED=1
 RUN npm run build
 
 # Vérifier que le dossier standalone a été créé
-RUN ls -la .next/standalone || (echo "ERROR: .next/standalone not found!" && exit 1)
+#RUN ls -la .next/standalone || (echo "ERROR: .next/standalone not found!" && exit 1)
 
 # Étape 2 : Runner
 FROM node:22.17.0-slim AS runner
